my:
    age: 24
    birthday: 07-28
    name: Liujiang
my1:
    age: 12
    greeting: hi,i'm  ${my.name}
    max: ${random.int(10)}
    name: forezp
    number: ${random.int}
    uuid: ${random.uuid}
    value: ${random.value}
spring:
    profiles:
        active: dev
